// String baseUrlX = "https://antrian.servicesimager.my.id/api";
// String baseUrlX = "http://antrean-app.test/api";
String baseUrlX = "http://queue-app.test:90/api";
String costumerServices = "$baseUrlX/code-queue";
String costumerPickQueue = "$baseUrlX/costumer-queue";
String loginUser = "$baseUrlX/auth/login";
String getRoleUserUrl = "$baseUrlX/get-role";
String getPickAssigment = "$baseUrlX/chose-assignment";
String pickQueueUrl = "$baseUrlX/pick-queue";
String viewQueueUserUrl = "$baseUrlX/test-view-queue";
String viewQueueSingleUserUrl = "$baseUrlX/view-queue-user";
String confirmQueueUserUrl = "$baseUrlX/confirm-queue-user";
String skipQueueUserUrl = "$baseUrlX/skip-queue-user";
String recallQueueUserUrl = "$baseUrlX/recall-queue-user";
String getAssignmentToday = "$baseUrlX/assignment/";
String deleteAssignmentToday = "$baseUrlX/assignment";
String supabaseUrl = 'https://pyosfrtvbyktxrvduvek.supabase.co';
String supabaseAnonKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5b3NmcnR2YnlrdHhydmR1dmVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDAzMTU0NTcsImV4cCI6MjAxNTg5MTQ1N30.WpM4fyxs7RvyuexxkdupsqakpBCRunRkC7XYHYhMHT4';
