// String baseUrlX = "https://antrian.servicesimager.my.id/api";
String baseUrlX = "http://antrean-app.test/api";
String costumerServices = "$baseUrlX/code-queue";
String costumerPickQueue = "$baseUrlX/costumer-queue";
String loginUser = "$baseUrlX/auth/login";
String getRoleUserUrl = "$baseUrlX/get-role";
String getPickAssigment = "$baseUrlX/chose-assignment";
String pickQueueUrl = "$baseUrlX/pick-queue";
String viewQueueUserUrl = "$baseUrlX/test-view-queue";
